###################################
###    initialization of
###
###    cask_args appdir: '/Applications'
###    tap 'caskroom/cask'
###    tap 'telemachus/brew', 'https://telemachus@bitbucket.org/telemachus/brew.git'
###    brew 'imagemagick'
###    brew 'mysql', restart_service: true, conflicts_with: ['homebrew/versions/mysql56']
###    brew 'emacs', args: ['with-cocoa', 'with-gnutls']
###    cask 'google-chrome'
###    cask 'java' unless system '/usr/libexec/java_home --failfast'
###    cask 'firefox', args: { appdir: '~/my-apps/Applications' }
###    mas '1Password', id: 443987910
###################################

cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'autoconf'
brew 'xz'
brew 'automake'
brew 'awscli'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'dirmngr'
brew 'pkg-config'
brew 'pcre'
brew 'gettext'
brew 'git'
brew 'x264'
brew 'lame'
brew 'xvid'
brew 'libpng'
brew 'freetype'
brew 'openssl'
brew 'ffmpeg'
brew 'flow'
brew 'gdbm'
brew 'git-extras'
brew 'gmp'
brew 'gnu-getopt'
brew 'gnupg'
brew 'pinentry'
brew 'gpg-agent'
brew 'libusb'
brew 'libusb-compat'
brew 'readline'
brew 'gnupg2'
brew 'libtasn1'
brew 'nettle'
brew 'gnutls'
brew 'go'
brew 'htop'
brew 'libtool'
brew 'jpeg'
brew 'libtiff'
brew 'imagemagick'
brew 'json-c'
brew 'lastpass-cli'
brew 'libyaml'
brew 'libyubikey'
brew 'mackup'
brew 'mtr'
brew 'tokyo-cabinet'
brew 'mutt'
brew 'node'
brew 'p7zip'
brew 'pwgen'
brew 'tree'
brew 'pass'
brew 'sqlite'
brew 'python'
brew 'unrar'
brew 'vim'
brew 'watchman'
brew 'wget'
brew 'ykpers'

cask 'adium'
cask 'adobe-creative-cloud'
cask 'alternote'
cask 'atom'
cask 'bittorrent-sync'
cask 'black-screen'
cask 'cd-to'
cask 'dnscrypt'
cask 'dockertoolbox'
cask 'dropbox'
cask 'firefox'
cask 'gmvault'
cask 'google-chrome'
cask 'google-hangouts'
cask 'google-web-designer'
cask 'gpgtools'
cask 'handbrakecli'
cask 'imageoptim'
cask 'istat-menus'
cask 'java'
cask 'kodi'
cask 'little-snitch'
cask 'logmein-client'
cask 'nzbvortex'
cask 'omnifocus'
cask 'osxfuse'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'sqlitestudio'
cask 'sshfs'
cask 'steam'
cask 'tower'
cask 'transmit'
cask 'tunnelblick'
cask 'unetbootin'
cask 'utorrent'
cask 'virtualbox'
cask 'vlc'
cask 'vmware-fusion'
cask 'wireshark'
cask 'yubikey-personalization-gui'
