#!/bin/bash

# debian specific aliases
#alias open='browser-exec "$@"'
#alias pbcopy='xclip -selection clipboard'
#alias pbpaste='xclip -selection clipboard -o'

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Shortcuts
alias dl="cd ~/Downloads"
alias g="git"
alias h="history"

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# IP addresses
alias pubip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="sudo ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ips="sudo ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# OS X has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# OS X has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK)
alias afk="i3lock -c 000000"

# vhosts
alias hosts='sudo vim /etc/hosts'

# untar
alias untar='tar xzvf'

#uesr shorts
alias raz="rsync -azP --no-compress"
alias gpg="gpg2"
alias edinit="atom ~/owncloud/Devlo/dev-init"
alias vi="vim"

#Editing Shortcuts
alias xssh="v ~/.ssh/config"
alias xdots="v ~/.dotset"

#Dotfiles
alias dots='git --git-dir=$HOME/.dots/ --work-tree=$HOME'
alias dotss='dots commit -av '
alias dotsup="dots submodule foreach git pull origin master"

###### PROJECTS #############
alias own="cd ~/ownCloud"
alias owndev="cd ~/ownCloud/Devlo"
alias pay="cd ~/Develop/Payables; ls"
alias ag="cd ~/Develop/AdGreetz; ls"

###### BREW STUF ######
alias brewed="cd ~/.dotset; brew bundle dump --force"
